# Generated by Django 4.1.2 on 2022-10-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('steep_time', models.IntegerField(default=120)),
                ('steep_temp', models.IntegerField(default=112)),
                ('tsp_per_cup', models.FloatField(default=1)),
            ],
        ),
    ]
