
# This Dockerfile was generated by Skelebot
# Editing this file manually is not advised as all changes will be overwritten by Skelebot

FROM skelebot/python-base:3.8
MAINTAINER Sean Shookman <SMS112788@gmail.com>
WORKDIR /app
RUN ["pip", "install", "django~=4.1"]
COPY . /app
CMD /bin/bash -c "bash jobs/run.sh"
